---
title: "Manuscritp Air Quality"
author: "Maximilian Grau"
date: "24/11/2021"
output: 
  html_document: 
    toc: yes
    highlight: espresso
    theme: flatly
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Background

This exercise is part of the workshop by the Global Health Engineering Group at ETH Zurich.

```{r}

library(readr)
library(dplyr)
library(DT)
library(lubridate)
library(ggplot2)

```

# Data

```{r}

data_link <- "https://raw.githubusercontent.com/Global-Health-Engineering/manuscript-hospital-air-quality/main/data/intermediate/malawi-hospitals-air-quality.csv"

data_in <- read_csv(data_link)

```

# Exercise 1

```{r transform-summary}

dat_in_sum_day <- data_in %>% 
  filter(value <= 1000) %>% 
  mutate(date = as_date(date_time)) %>% 
  group_by(date, location, indicator) %>% 
  summarise(min = min(value),
            median = median(value),
            mean = mean(value),
            sd = sd(value),
            max = max(value))


```

```{r}

dat_in_sum_day %>%
  datatable()


```

# Exercise 2

- Can you also reproduce the plot that we created in unit 2 of application exercise 2?

```{r}

ggplot(data = dat_in_sum_day,
       mapping = aes(x = date, 
                     y = mean, 
                     color = indicator)) +
  geom_point(size = 1.0) +
  geom_line() +
  labs(title = "Hospital Air Quality",
       subtitle = "Mean 24-hour PM2.5 and PM10 concentrations at eight locations") +
  ylab(bquote(uq/m^3)) +
  facet_wrap(~location) +
  theme_bw(base_size = 10) 

```

